export interface Token {
  section: "New Pairs" | "Final Stretch" | "Migrated"
  name: string
  fullName: string
  symbol: string
  price: string
  priceUSD: string
  marketCap: string
  change24h: string
  volume24h: string
  time: string
  icon: string
  holders: string
  tags: string[]
  change24hValue: number
  volume24hValue: number
  holdersValue: number
}

export const tokenData = [
  // New Pairs
  {
    section: "New Pairs",
    name: "Hopium",
    fullName: "The Art of Hopium",
    symbol: "HOP",
    price: "$3.55K",
    priceUSD: "$60",
    marketCap: "MC",
    change24h: "+2%",
    volume24h: "2%",
    time: "2s",
    icon: "🟠",
    holders: "1",
    tags: ["PI", "P2", "P3"],
    change24hValue: 2,
    volume24hValue: 2,
    holdersValue: 1,
  },
  {
    section: "New Pairs",
    name: "Hodler",
    fullName: "Hodler",
    symbol: "HOD",
    price: "$4.11K",
    priceUSD: "$850",
    marketCap: "MC",
    change24h: "0%",
    volume24h: "22d",
    time: "8s",
    icon: "👤",
    holders: "0",
    tags: ["PI", "P2", "P3"],
    change24hValue: 0,
    volume24hValue: 0,
    holdersValue: 0,
  },
  {
    section: "New Pairs",
    name: "Hodler",
    fullName: "Hodler",
    symbol: "HOD",
    price: "$3.44K",
    priceUSD: "$16",
    marketCap: "MC",
    change24h: "0%",
    volume24h: "0%",
    time: "13s",
    icon: "👤",
    holders: "0",
    tags: ["PI", "P2", "P3"],
    change24hValue: 0,
    volume24hValue: 0,
    holdersValue: 0,
  },
  {
    section: "New Pairs",
    name: "PHANTOMv2",
    fullName: "Phantomv2",
    symbol: "PHAN",
    price: "$3.56K",
    priceUSD: "$258",
    marketCap: "MC",
    change24h: "+2%",
    volume24h: "1%",
    time: "14s",
    icon: "👻",
    holders: "3",
    tags: ["PI", "P2", "P3"],
    change24hValue: 2,
    volume24hValue: 1,
    holdersValue: 3,
  },
  {
    section: "New Pairs",
    name: "HODLCAT",
    fullName: "HODLCAT",
    symbol: "HODL",
    price: "$4.15K",
    priceUSD: "$605",
    marketCap: "MC",
    change24h: "+2%",
    volume24h: "1%",
    time: "14s",
    icon: "🐱",
    holders: "1",
    tags: ["PI", "P2", "P3"],
    change24hValue: 2,
    volume24hValue: 1,
    holdersValue: 1,
  },
  // Final Stretch
  {
    section: "Final Stretch",
    name: "Coca-Cola",
    fullName: "Coca-Cola",
    symbol: "COKE",
    price: "$711K",
    priceUSD: "$18",
    marketCap: "MC",
    change24h: "+19%",
    volume24h: "0%",
    time: "5m",
    icon: "🔴",
    holders: "286",
    tags: ["PI", "P2", "P3"],
    change24hValue: 19,
    volume24hValue: 0,
    holdersValue: 286,
  },
  {
    section: "Final Stretch",
    name: "Bags",
    fullName: "Bags",
    symbol: "BAG",
    price: "$29.8K",
    priceUSD: "$10",
    marketCap: "MC",
    change24h: "+9%",
    volume24h: "0%",
    time: "27m",
    icon: "👜",
    holders: "196",
    tags: ["PI", "P2", "P3"],
    change24hValue: 9,
    volume24hValue: 0,
    holdersValue: 196,
  },
  {
    section: "Final Stretch",
    name: "snowball",
    fullName: "snowball",
    symbol: "SNOW",
    price: "$24.5K",
    priceUSD: "$27",
    marketCap: "MC",
    change24h: "+21%",
    volume24h: "0%",
    time: "45m",
    icon: "❄️",
    holders: "202",
    tags: ["PI", "P2", "P3"],
    change24hValue: 21,
    volume24hValue: 0,
    holdersValue: 202,
  },
  {
    section: "Final Stretch",
    name: "KAYI",
    fullName: "Live and Confused Coin",
    symbol: "KAYI",
    price: "$34.4K",
    priceUSD: "$39",
    marketCap: "MC",
    change24h: "+73%",
    volume24h: "0%",
    time: "2d",
    icon: "😵",
    holders: "9",
    tags: ["PI", "P2", "P3"],
    change24hValue: 73,
    volume24hValue: 0,
    holdersValue: 9,
  },
  {
    section: "Final Stretch",
    name: "BONKEY",
    fullName: "BONKEY",
    symbol: "BON",
    price: "$41K",
    priceUSD: "$10",
    marketCap: "MC",
    change24h: "0%",
    volume24h: "0%",
    time: "2h",
    icon: "🦍",
    holders: "38",
    tags: ["PI", "P2", "P3"],
    change24hValue: 0,
    volume24hValue: 0,
    holdersValue: 38,
  },
  // Migrated
  {
    section: "Migrated",
    name: "PORNHUB",
    fullName: "PORNHUB OFFICIAL",
    symbol: "XXX",
    price: "$42K",
    priceUSD: "$11",
    marketCap: "MC",
    change24h: "+75%",
    volume24h: "0%",
    time: "1s",
    icon: "P",
    holders: "6",
    tags: ["PI", "P2", "P3"],
    change24hValue: 75,
    volume24hValue: 0,
    holdersValue: 6,
  },
  {
    section: "Migrated",
    name: "RACER",
    fullName: "RACER",
    symbol: "RAC",
    price: "$43.9K",
    priceUSD: "$3",
    marketCap: "MC",
    change24h: "+100%",
    volume24h: "0%",
    time: "14s",
    icon: "🏁",
    holders: "4",
    tags: ["PI", "P2", "P3"],
    change24hValue: 100,
    volume24hValue: 0,
    holdersValue: 4,
  },
  {
    section: "Migrated",
    name: "FARTv2",
    fullName: "Fartfun v2",
    symbol: "FART",
    price: "$643K",
    priceUSD: "$1",
    marketCap: "MC",
    change24h: "+100%",
    volume24h: "19%",
    time: "45s",
    icon: "💨",
    holders: "4",
    tags: ["PI", "P2", "P3"],
    change24hValue: 100,
    volume24hValue: 19,
    holdersValue: 4,
  },
  {
    section: "Migrated",
    name: "TheTachi",
    fullName: "the savior of the trenches",
    symbol: "TAC",
    price: "$1.4M",
    priceUSD: "$27",
    marketCap: "MC",
    change24h: "+98%",
    volume24h: "0%",
    time: "1m",
    icon: "⚔️",
    holders: "121",
    tags: ["PI", "P2", "P3"],
    change24hValue: 98,
    volume24hValue: 0,
    holdersValue: 121,
  },
  {
    section: "Migrated",
    name: "MWC",
    fullName: "Meme Warfare Center",
    symbol: "MWC",
    price: "$56.5K",
    priceUSD: "$13",
    marketCap: "MC",
    change24h: "0%",
    volume24h: "0%",
    time: "1m",
    icon: "⚔️",
    holders: "72",
    tags: ["PI", "P2", "P3"],
    change24hValue: 0,
    volume24hValue: 0,
    holdersValue: 72,
  },
] as const satisfies readonly Token[]
