export interface Token {
  section: "New Pairs" | "Final Stretch" | "Migrated";
  name: string;
  fullName: string;
  symbol: string;
  price: string;
  priceUSD: string;
  marketCap: string;
  change24h: string;
  volume24h: string;
  time: string;
  icon: string;
  holders: string;
  tags: string[];
  change24hValue: number;
  volume24hValue: number;
  holdersValue: number;
}

export const tokenData = [
  // New Pairs - Recently launched tokens
  {
    section: "New Pairs",
    name: "SolanaBot",
    fullName: "Solana Trading Bot",
    symbol: "SBOT",
    price: "$2.8M",
    priceUSD: "$0.0045",
    marketCap: "MC",
    change24h: "+156%",
    volume24h: "12.3K",
    time: "5m",
    icon: "🤖",
    holders: "89",
    tags: ["AI", "BOT", "SOL"],
    change24hValue: 156,
    volume24hValue: 12300,
    holdersValue: 89,
  },
  {
    section: "New Pairs",
    name: "MoonDoge",
    fullName: "Moon Doge Protocol",
    symbol: "MDOGE",
    price: "$1.2M",
    priceUSD: "$0.00234",
    marketCap: "MC",
    change24h: "+89%",
    volume24h: "8.7K",
    time: "12m",
    icon: "�",
    holders: "156",
    tags: ["MEME", "DOGE", "MOON"],
    change24hValue: 89,
    volume24hValue: 8700,
    holdersValue: 156,
  },
  {
    section: "New Pairs",
    name: "AIVision",
    fullName: "AI Vision Token",
    symbol: "AIVI",
    price: "$3.5M",
    priceUSD: "$0.0078",
    marketCap: "MC",
    change24h: "+234%",
    volume24h: "15.2K",
    time: "18m",
    icon: "�️",
    holders: "203",
    tags: ["AI", "VISION", "ML"],
    change24hValue: 234,
    volume24hValue: 15200,
    holdersValue: 203,
  },
  {
    section: "New Pairs",
    name: "PepeCoin",
    fullName: "Pepe The Frog",
    symbol: "PEPE",
    price: "$5.1M",
    priceUSD: "$0.000567",
    marketCap: "MC",
    change24h: "+67%",
    volume24h: "22.8K",
    time: "25m",
    icon: "�",
    holders: "312",
    tags: ["MEME", "PEPE", "FROG"],
    change24hValue: 67,
    volume24hValue: 22800,
    holdersValue: 312,
  },
  {
    section: "New Pairs",
    name: "DegenApe",
    fullName: "Degen Ape Club",
    symbol: "DAPE",
    price: "$4.3M",
    priceUSD: "$0.0123",
    marketCap: "MC",
    change24h: "+145%",
    volume24h: "18.6K",
    time: "32m",
    icon: "🦍",
    holders: "187",
    tags: ["NFT", "APE", "DEGEN"],
    change24hValue: 145,
    volume24hValue: 18600,
    holdersValue: 187,
  },
  {
    section: "New Pairs",
    name: "MetaCat",
    fullName: "Meta Cat Universe",
    symbol: "MCAT",
    price: "$2.1M",
    priceUSD: "$0.00891",
    marketCap: "MC",
    change24h: "+78%",
    volume24h: "9.4K",
    time: "45m",
    icon: "🐱",
    holders: "134",
    tags: ["META", "CAT", "GAMING"],
    change24hValue: 78,
    volume24hValue: 9400,
    holdersValue: 134,
  },

  // Final Stretch - Tokens nearing major milestones
  {
    section: "Final Stretch",
    name: "SafeMoon",
    fullName: "SafeMoon Protocol",
    symbol: "SAFEMOON",
    price: "$45.2M",
    priceUSD: "$0.456",
    marketCap: "MC",
    change24h: "+23%",
    volume24h: "125K",
    time: "2h",
    icon: "🌙",
    holders: "1.2K",
    tags: ["SAFE", "MOON", "DeFi"],
    change24hValue: 23,
    volume24hValue: 125000,
    holdersValue: 1200,
  },
  {
    section: "Final Stretch",
    name: "ElonDoge",
    fullName: "Elon Musk Doge",
    symbol: "EDOGE",
    price: "$32.8M",
    priceUSD: "$0.234",
    marketCap: "MC",
    change24h: "+35%",
    volume24h: "89K",
    time: "3h",
    icon: "�",
    holders: "856",
    tags: ["ELON", "DOGE", "TESLA"],
    change24hValue: 35,
    volume24hValue: 89000,
    holdersValue: 856,
  },
  {
    section: "Final Stretch",
    name: "CryptoKitty",
    fullName: "Crypto Kitty Coin",
    symbol: "KITTY",
    price: "$28.5M",
    priceUSD: "$0.678",
    marketCap: "MC",
    change24h: "+18%",
    volume24h: "67K",
    time: "4h",
    icon: "🐾",
    holders: "743",
    tags: ["NFT", "KITTY", "CUTE"],
    change24hValue: 18,
    volume24hValue: 67000,
    holdersValue: 743,
  },
  {
    section: "Final Stretch",
    name: "DiamonHands",
    fullName: "Diamond Hands Token",
    symbol: "DIAMOND",
    price: "$67.3M",
    priceUSD: "$1.23",
    marketCap: "MC",
    change24h: "+42%",
    volume24h: "156K",
    time: "5h",
    icon: "�",
    holders: "2.1K",
    tags: ["HODL", "DIAMOND", "STRONG"],
    change24hValue: 42,
    volume24hValue: 156000,
    holdersValue: 2100,
  },
  {
    section: "Final Stretch",
    name: "RocketFuel",
    fullName: "Rocket Fuel Protocol",
    symbol: "FUEL",
    price: "$54.7M",
    priceUSD: "$0.89",
    marketCap: "MC",
    change24h: "+28%",
    volume24h: "98K",
    time: "6h",
    icon: "⛽",
    holders: "1.8K",
    tags: ["ROCKET", "FUEL", "BOOST"],
    change24hValue: 28,
    volume24hValue: 98000,
    holdersValue: 1800,
  },

  // Migrated - Successfully launched tokens
  {
    section: "Migrated",
    name: "ShibaInu",
    fullName: "Shiba Inu",
    symbol: "SHIB",
    price: "$892M",
    priceUSD: "$12.34",
    marketCap: "MC",
    change24h: "+15%",
    volume24h: "2.3M",
    time: "1d",
    icon: "🐕",
    holders: "15.6K",
    tags: ["MEME", "SHIBA", "POPULAR"],
    change24hValue: 15,
    volume24hValue: 2300000,
    holdersValue: 15600,
  },
  {
    section: "Migrated",
    name: "FlokiInu",
    fullName: "Floki Inu",
    symbol: "FLOKI",
    price: "$456M",
    priceUSD: "$8.91",
    marketCap: "MC",
    change24h: "+12%",
    volume24h: "1.8M",
    time: "2d",
    icon: "🐺",
    holders: "12.3K",
    tags: ["FLOKI", "INU", "VIKING"],
    change24hValue: 12,
    volume24hValue: 1800000,
    holdersValue: 12300,
  },
  {
    section: "Migrated",
    name: "BabyDoge",
    fullName: "Baby Doge Coin",
    symbol: "BABYDOGE",
    price: "$234M",
    priceUSD: "$3.45",
    marketCap: "MC",
    change24h: "+8%",
    volume24h: "890K",
    time: "3d",
    icon: "�",
    holders: "8.7K",
    tags: ["BABY", "DOGE", "CHARITY"],
    change24hValue: 8,
    volume24hValue: 890000,
    holdersValue: 8700,
  },
  {
    section: "Migrated",
    name: "SafeMars",
    fullName: "SafeMars Protocol",
    symbol: "SAFEMARS",
    price: "$678M",
    priceUSD: "$15.67",
    marketCap: "MC",
    change24h: "+22%",
    volume24h: "3.4M",
    time: "5d",
    icon: "🔴",
    holders: "23.4K",
    tags: ["SAFE", "MARS", "SPACE"],
    change24hValue: 22,
    volume24hValue: 3400000,
    holdersValue: 23400,
  },
  {
    section: "Migrated",
    name: "DogeKing",
    fullName: "Doge King Token",
    symbol: "DOGEKING",
    price: "$1.2B",
    priceUSD: "$45.23",
    marketCap: "MC",
    change24h: "+35%",
    volume24h: "5.6M",
    time: "1w",
    icon: "👑",
    holders: "34.5K",
    tags: ["DOGE", "KING", "ROYAL"],
    change24hValue: 35,
    volume24hValue: 5600000,
    holdersValue: 34500,
  },
] as const satisfies readonly Token[];
